# Generated by Django 3.0.6 on 2020-06-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='deiscount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
