# Generated by Django 3.0.7 on 2020-06-18 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
