# Generated by Django 3.0.7 on 2020-06-20 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200620_1144'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coupen',
            new_name='Coupon',
        ),
    ]
