# Generated by Django 3.0.7 on 2020-06-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='email',
            field=models.EmailField(default='admin@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
