# Generated by Django 3.0.7 on 2020-06-21 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20200621_1543'),
        ('core', '0027_auto_20200621_1430'),
    ]

    operations = [
    ]
